/** Shared language list for navbar + translation target codes (Google Translate `tl`). */
export const languageOptions = [
  { code: "en", labelKey: "lang.en", flag: "GB" },
  { code: "ur", labelKey: "lang.ur", flag: "PK" },
  { code: "ar", labelKey: "lang.ar", flag: "SA" },
  { code: "fr", labelKey: "lang.fr", flag: "FR" },
  { code: "de", labelKey: "lang.de", flag: "DE" },
  { code: "es", labelKey: "lang.es", flag: "ES" },
  { code: "it", labelKey: "lang.it", flag: "IT" },
  { code: "pt", labelKey: "lang.pt", flag: "PT" },
  { code: "ru", labelKey: "lang.ru", flag: "RU" },
  { code: "tr", labelKey: "lang.tr", flag: "TR" },
  { code: "fa", labelKey: "lang.fa", flag: "IR" },
  { code: "hi", labelKey: "lang.hi", flag: "IN" },
  { code: "bn", labelKey: "lang.bn", flag: "BD" },
  { code: "zh-CN", labelKey: "lang.zh-CN", flag: "CN" },
  { code: "zh-TW", labelKey: "lang.zh-TW", flag: "TW" },
  { code: "ja", labelKey: "lang.ja", flag: "JP" },
  { code: "ko", labelKey: "lang.ko", flag: "KR" },
  { code: "th", labelKey: "lang.th", flag: "TH" },
  { code: "vi", labelKey: "lang.vi", flag: "VN" },
  { code: "id", labelKey: "lang.id", flag: "ID" },
  { code: "ms", labelKey: "lang.ms", flag: "MY" },
  { code: "nl", labelKey: "lang.nl", flag: "NL" },
  { code: "sv", labelKey: "lang.sv", flag: "SE" },
  { code: "pl", labelKey: "lang.pl", flag: "PL" },
  { code: "uk", labelKey: "lang.uk", flag: "UA" },
];
