/** Shared language list for navbar + translation target codes (Google Translate `tl`). */
export const languageOptions = [
  { code: "en", label: "English", flag: "GB" },
  { code: "ur", label: "Urdu", flag: "PK" },
  { code: "ar", label: "Arabic", flag: "SA" },
  { code: "fr", label: "French", flag: "FR" },
  { code: "de", label: "German", flag: "DE" },
  { code: "es", label: "Spanish", flag: "ES" },
  { code: "it", label: "Italian", flag: "IT" },
  { code: "pt", label: "Portuguese", flag: "PT" },
  { code: "ru", label: "Russian", flag: "RU" },
  { code: "tr", label: "Turkish", flag: "TR" },
  { code: "fa", label: "Persian", flag: "IR" },
  { code: "hi", label: "Hindi", flag: "IN" },
  { code: "bn", label: "Bengali", flag: "BD" },
  { code: "zh-CN", label: "Chinese (Simplified)", flag: "CN" },
  { code: "zh-TW", label: "Chinese (Traditional)", flag: "TW" },
  { code: "ja", label: "Japanese", flag: "JP" },
  { code: "ko", label: "Korean", flag: "KR" },
  { code: "th", label: "Thai", flag: "TH" },
  { code: "vi", label: "Vietnamese", flag: "VN" },
  { code: "id", label: "Indonesian", flag: "ID" },
  { code: "ms", label: "Malay", flag: "MY" },
  { code: "nl", label: "Dutch", flag: "NL" },
  { code: "sv", label: "Swedish", flag: "SE" },
  { code: "pl", label: "Polish", flag: "PL" },
  { code: "uk", label: "Ukrainian", flag: "UA" },
];
