/**
 * English source strings for site-wide translation. Keys are stable; values are translated via /api/translate.
 */
export const SITE_STRINGS = {
  // Navbar
  "nav.about_us": "About us",
  "nav.roadmap": "Roadmap",
  "nav.membership": "Membership",
  "nav.faqs": "FAQs",
  "nav.login": "Login",
  "nav.cta": "Get started for Free",
  "app.translating": "Translating interface…",
  "nav.language": "Language",
  "nav.translating": "Translating…",
  "nav.open_menu": "Open main menu",
  "nav.lang_options": "Language options",

  // Hero
  "hero.title": "The Future Of Financial Growth",
  "hero.body":
    "Quantro Network is more than fintech, it's a premium membership club designed for visionaries who want access to the same wealth-creation tools once reserved for institutions. As a member, you gain entry into a private ecosystem where innovation meets opportunity: advanced automated trading technology, exclusive financial insights, and a supportive education hub built to sharpen your edge in today's markets.",
  "hero.cta": "Join Quantro Network",
  "hero.trusted": "Trusted by professional traders worldwide",
  "hero.alt_left": "Hero left white cards",
  "hero.alt_right": "Hero right white cards",

  // Wealth
  "wealth.eyebrow": "The Future of Financial Growth",
  "wealth.title": "Wealth. Knowledge.\nAccess.",
  "wealth.body":
    "we believe real growth happens when technology and education work hand-in-hand. That's why every membership includes access to our suite of expertly engineered trading tools, while also connecting you to a structured learning environment where beginners and experienced traders alike can thrive.",
  "wealth.img_alt": "Wealth Section",

  // How it works
  "hiw.eyebrow": "THE FUTURE OF INTELLIGENT AUTOMATION",
  "hiw.title": "How Quantro Network Works",
  "hiw.step1_title": "Step 1: Join the Quantro Membership",
  "hiw.step1_body":
    "Begin your journey by entering a strategic collaboration with Quantro Network. Upon joining, you unlock privileged entry to a selective marketplace designed for forward-thinking traders and investors.",
  "hiw.step2_title": "Step 2: Fund Your Account",
  "hiw.step2_body":
    "Proceed by adding the minimum required funds to your secure wallet via any of our supported payment options. This capital becomes the operational foundation for activating and managing your Expert Advisor licenses.",
  "hiw.step3_title": "Step 3: Choose one or more Expert Advisors",
  "hiw.step3_body":
    "Select your preferred automated trading tool (Expert Advisor) that aligns with your financial goals and risk tolerance. Quantro Network offers a range of sophisticated systems crafted to suit diverse objectives.",
  "hiw.step4_title": "Step 4: Activate Your License",
  "hiw.step4_body":
    "Once your account is funded, activate your chosen Expert Advisor license. Follow the guided steps to securely connect it to your funded account, allowing it to operate autonomously within your defined parameters.",
  "hiw.step5_title": "Step 5: Monitor and Experience the performance through Real time dashboard",
  "hiw.step5_body":
    "Track your Expert Advisor's performance through your dashboard in real time. Observe trades, analytics, and results as your automated strategy works on your behalf around the clock.",

  // Split feature
  "split.eyebrow": "Premium Membership Access",
  "split.title": "Monthly or quarterly gateway to elite automation tools.",
  "split.body":
    "It's time to leverage the power of automation tools and gain access to institutional-grade tools that were once reserved for Wall Street. Start building wealth with our sophisticated automation tools.",
  "split.cta_primary": "Get started now",
  "split.cta_secondary": "Learn More",
  "split.img_alt": "Monitor Mockup",

  // Data streams
  "data.eyebrow": "Transparent API Connectivity",
  "data.title": "Live, verifiable data streams directly from global markets.",
  "data.body":
    "Experience seamless integration with live, verifiable data streams sourced directly from global markets ensuring accuracy, speed, and trust in every connection.",
  "data.cta": "Get started now",
  "data.img_alt": "Quantro Atlas Mockups",

  // Engineering
  "eng.eyebrow": "Cutting-Edge Engineering",
  "eng.title": "Developed by a team of developers, analysts, and digital architects.",
  "eng.body":
    "Behind every feature is a multidisciplinary team dedicated to refining algorithms, validating data integrity, and shaping an experience that stays ahead of market complexity—so members can focus on strategy, not infrastructure.",
  "eng.cta_join": "Join Premium Membership",
  "eng.cta_view": "View Membership Options",
  "eng.phone_alt": "Quantro Subscriber Portal on mobile",

  // Partners / presentations
  "partners.title": "Company Presentation",
  "partners.subtitle": "Download our comprehensive company presentation in your preferred language",
  "partners.view_pdf": "View PDF",
  "partners.download": "Download",

  // Documentation CTA
  "docs.title": "Need More Information?",
  "docs.body": "Check out our comprehensive documentation for detailed guides and resources",
  "docs.cta": "View Documentation",

  // FAQ (home section)
  "faq.eyebrow": "FREQUENTLY ASKED QUESTIONS",
  "faq.title": "Frequently asked questions",
  "faq.intro_before": "Looking for something else? Chat with us via",
  "faq.intro_after": "and we will try our best to help you with your questions!",
  "faq.q0": "What is Quantro Network?",
  "faq.a0":
    "Quantro Network is a premium membership ecosystem that combines institutional-grade automation tools, market intelligence, and structured education so members can access professional workflows in one place.",
  "faq.q1": "How is Quantro Network different from other platforms?",
  "faq.a1":
    "We focus on verified data connectivity, transparent tooling, and a curated membership model—not generic signals. Our stack is built for serious operators who want depth, not noise.",
  "faq.q2": "Do I need trading experience to get started?",
  "faq.a2":
    "No. Beginners can follow guided onboarding and education tracks, while experienced traders can go straight to advanced automation and analytics.",
  "faq.q3": "How do I contact support?",
  "faq.a3":
    "Email us anytime at support@quantronetwork.com and our team will help with account, billing, or technical questions.",
  "faq.q4": "Is my data secure?",
  "faq.a4":
    "We apply industry-standard security practices for accounts and integrations. You control permissions and can review activity from your dashboard.",

  // Footer
  "footer.news_title": "Stay Ahead of the Market",
  "footer.news_desc":
    "Subscribe to receive exclusive market insights, trading strategies, and early access to new features that can help maximize your returns.",
  "footer.email_label": "Email address",
  "footer.email_ph": "Enter your email*",
  "footer.subscribe": "Subscribe",
  "footer.col_company": "Company",
  "footer.col_corporate": "Corporate",
  "footer.col_legal": "Legal & Compliance",
  "footer.col_help": "Help Center",
  "footer.link_about": "About Quantro Network",
  "footer.link_mission": "Our Mission",
  "footer.link_roadmap": "Strategic Roadmap",
  "footer.link_compliance": "Compliance & Operational Architecture",
  "footer.link_membership": "Membership Plans",
  "footer.link_terms": "Terms & Conditions",
  "footer.link_privacy": "Privacy Policy",
  "footer.link_risk": "Risk Disclosure",
  "footer.link_academy": "QN Academy",
  "footer.link_guide": "Get Started Guide",
  "footer.link_faq": "FAQ",
  "footer.link_support": "Contact Support",
  "footer.connect": "Connect",
  "footer.newsletter_heading": "Stay updated with our newsletter",
  "footer.mini_email_label": "Newsletter email",
  "footer.mini_email_ph": "Email",
  "footer.copyright": "Copyright © {year} Quantro Network. All rights reserved.",
  "footer.tagline":
    "Quantro Network's Expert Advisors are engineered as high-performance wealth-creation systems—purpose-built to execute, optimize, and grow wealth with precision. They don't guide decisions; they automate them.",

  // Secondary pages
  "page.about.title": "About Us",
  "page.about.body":
    "Quantro Network is a premium ecosystem focused on modern trading tools, education, and private access for ambitious investors.",
  "page.login.title": "Login",
  "page.login.body": "Authentication form section can be implemented here.",
  "page.get_started.title": "Get Started",
  "page.get_started.body": "Onboarding steps, free trial details, and signup actions can go here.",
  "page.membership.title": "Membership",
  "page.membership.body": "Membership details, tiers, and premium benefits can be added here.",

  // Membership page
  "membership.eyebrow": "QUANTRO MEMBERSHIP PACKAGES",
  "membership.hero_title": "Access real-time intelligence and analytics",
  "membership.promo":
    "🎉 This is a 90 days pre-launch special offer Limited time pricing - Get started before launch!",
  "membership.access_title": "Access Quarterly",
  "membership.access_price": "$99",
  "membership.access_period": "/ Quarterly",
  "membership.access_cta": "Get Started Now",
  "membership.prime_title": "Prime Quarterly",
  "membership.prime_price": "$199",
  "membership.prime_period": "/ Quarterly",
  "membership.prime_cta": "Get Started Now",
  "membership.access_f1": "Real-time market intelligence dashboard",
  "membership.access_f2": "Core analytics & verified data streams",
  "membership.access_f3": "Standard support & onboarding guidance",
  "membership.access_f4": "Quarterly membership billing flexibility",
  "membership.access_f5": "QN Academy foundational learning tracks",
  "membership.access_f6": "Single-device dashboard access",
  "membership.access_f7": "Community forum & member updates",
  "membership.prime_f1": "Everything in Access, plus premium tooling",
  "membership.prime_f2": "Advanced analytics & expanded signals",
  "membership.prime_f3": "Priority support & faster response times",
  "membership.prime_f4": "Multi-license Expert Advisor overview",
  "membership.prime_f5": "Premium education & strategy content",
  "membership.prime_f6": "Extended historical data & exports",
  "membership.prime_f7": "Early access to new platform features",
  "membership.trust": "Securely pay through our partners",
  "page.roadmap.title": "Roadmap",
  "page.roadmap.body":
    "This page is ready for your upcoming milestones, release phases, and feature timelines.",
  "page.faqs.title": "FAQs",
  "page.faqs.body": "Frequently asked questions and support answers can be organized on this page.",

  // FAQ page (/faqs)
  "faq_page.hero_title": "Quantro Network — Official FAQ",
  "faq_page.hero_subtitle": "Find answers to common questions about Quantro Network.",
  "faq_page.search_ph": "Search for questions...",
  "faq_page.no_results": "No questions match your search. Try different keywords or clear the filters.",
  "faq_page.filter_all": "All Questions",
  "faq_page.filter_general": "General",
  "faq_page.filter_billing": "Account & Billing",
  "faq_page.filter_technical": "Technical",
  "faq_page.support_title": "Still have questions?",
  "faq_page.support_body":
    "Our support team is ready to assist you with account, billing, or technical topics. Reach out and we will get back to you as soon as we can.",
  "faq_page.contact_cta": "Contact Support",
  "faq_page.cta_title": "Ready to get started?",
  "faq_page.cta_subtitle": "Explore our plans, join the membership, or open your member portal.",
  "faq_page.cta_pricing": "View pricing",
  "faq_page.cta_portal": "Open portal",
  "faq_page.q0": "What is Quantro Network?",
  "faq_page.a0":
    "Quantro Network is a premium membership ecosystem that combines institutional-grade automation (Expert Advisors), verified market data, and structured education—so members can operate with professional workflows in one place.",
  "faq_page.q1": "Do I need trading experience to get started?",
  "faq_page.a1":
    "No. Beginners can follow guided onboarding and learning tracks, while experienced traders can move quickly into automation, analytics, and advanced tooling.",
  "faq_page.q2": "How reliable are your market data feeds and expert advisors?",
  "faq_page.a2":
    "We prioritize transparent connectivity and operational monitoring. Performance depends on market conditions, configuration, and risk settings—your dashboard is built to surface activity clearly so you can review results over time.",
  "faq_page.q3": "Do your expert advisors guarantee profits or specific returns?",
  "faq_page.a3":
    "No. Trading involves risk. Expert Advisors automate execution within the parameters you set; outcomes are not guaranteed. Always use sizing and risk controls appropriate for your situation.",
  "faq_page.q4": "How does Quantro Network generate revenue?",
  "faq_page.a4":
    "Quantro Network is supported through membership plans and related services. This model helps us invest in platform reliability, security, education, and ongoing product development.",
  "faq_page.q5": "What makes Quantro different from other trading platforms?",
  "faq_page.a5":
    "We focus on verified data connectivity, curated membership access, and a transparent toolset—not generic noise. The goal is depth: serious workflows for members who want clarity and control.",
  "faq_page.q6": "How do subscriptions, billing, and renewals work?",
  "faq_page.a6":
    "Memberships are billed on a recurring schedule (for example, quarterly) depending on the plan you choose. You can manage billing details from your account area and contact support for invoice or payment questions.",

  // Terms & Conditions (/terms)
  "terms.hero_title": "Terms & Conditions",
  "terms.hero_subtitle": "Important legal terms governing your use of Quantro Network's services",
  "terms.s1_title": "1. Introduction",
  "terms.s1_body":
    'Quantro Network ("QN", "we", "us", or "our") provides technology services, software tools, and membership access to the Quantro platform and related resources. By accessing or using our services, website, or applications, you agree to be bound by these Terms & Conditions and our other policies referenced herein. If you do not agree, you must discontinue use immediately.',
  "terms.s2_title": "2. Eligibility",
  "terms.s2_body":
    "By accessing the Quantro Network platform, you represent and warrant that you are at least the age of majority in your jurisdiction, that you have the legal capacity to enter into this agreement, and that your registration and use comply with all applicable laws and regulations. You are solely responsible for determining whether your use of our services is lawful in your country or region.",
  "terms.s3_title": "3. Intellectual Property",
  "terms.s3_body":
    "All software, code, algorithms, documentation, branding, logos, user interfaces, and other materials made available through Quantro Network are owned by Quantro Network or its licensors and are protected by copyright, trademark, and other intellectual property laws. You receive a limited, non-exclusive, non-transferable, revocable license to access and use the platform for personal, non-commercial purposes in accordance with these terms. You may not copy, modify, reverse engineer, decompile, distribute, or create derivative works from our materials without prior written consent.",
  "terms.s4_title": "4. Product Nature",
  "terms.s4_body":
    "Quantro Network is a technology provider. We are not a broker, investment adviser, bank, or fiduciary. We do not provide personalized investment, tax, or legal advice. Any tools, automation (including Expert Advisors), market data, or educational content are provided for informational and operational purposes only. Trading and investing involve substantial risk of loss. Past performance does not guarantee future results. You should seek independent professional advice before making financial decisions.",
  "terms.s5_title": "5. User Responsibility",
  "terms.s5_body":
    "You are solely responsible for maintaining the confidentiality and security of your account credentials, for all activity that occurs under your account, and for configuring risk parameters, capital allocation, and integrations appropriately. You must notify us promptly of any unauthorized access or security breach. You agree not to misuse the platform, interfere with other users or infrastructure, or use the services for unlawful purposes.",
  "terms.s6_title": "6. Limitation of Liability",
  "terms.s6_body":
    "To the fullest extent permitted by applicable law, Quantro Network and its affiliates, officers, directors, employees, and partners shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of profits, revenues, data, goodwill, or business opportunities, arising from your use of or inability to use the services, even if advised of the possibility of such damages. Our aggregate liability for any claim arising out of these terms or the services shall not exceed the total fees paid by you to Quantro Network in the twelve (12) months preceding the event giving rise to the claim, except where such limitation is prohibited by law.",
  "terms.s7_title": "7. Modification of Terms",
  "terms.s7_body":
    "We reserve the right to update, modify, or replace these Terms & Conditions at any time at our sole discretion. Revised terms will be posted on this page with an updated effective date where applicable. Your continued use of the services after changes constitutes acceptance of the revised terms. If you do not agree, you must stop using the services and may close your account in accordance with our procedures.",
  "terms.legal_heading": "Legal disclaimer",
  "terms.legal_p1":
    "Quantro Network is a pure technology provider. We do not hold client funds for investment purposes, execute trades on your behalf as a principal, or guarantee any level of returns. Market participation involves risk, including the possible loss of principal. You acknowledge that you use our technology and any connected third-party services at your own risk.",
  "terms.legal_p2":
    "Nothing on this website or within the platform constitutes an offer or solicitation to buy or sell any financial instrument in any jurisdiction where such activity would be unlawful. You are responsible for compliance with the laws and regulations that apply to you.",
  "terms.legal_p3":
    "We strive to maintain reliable systems and accurate information but do not warrant uninterrupted access or error-free operation. Service availability may be affected by maintenance, third-party providers, or events beyond our reasonable control.",
  "terms.integrations_title": "Integration partners",
  "terms.integrations_intro":
    "At Quantro Network, we've integrated with multiple platforms and data providers to deliver connectivity, execution, and analytics for our members. Partnerships are selected to support reliability, transparency, and breadth of market coverage.",
  "terms.integrations_why_title": "Why we partner",
  "terms.integrations_why_1": "Data integrity — verified feeds and consistent formatting for downstream tools.",
  "terms.integrations_why_2": "Low latency — infrastructure aligned with timely market data and execution paths.",
  "terms.integrations_why_3": "Diverse market access — coverage across asset classes and regions where supported.",
  "terms.integrations_why_4": "Reliability — partners with operational maturity and monitoring suitable for professional workflows.",
  "terms.integrations_strat_title": "Strategic benefits",
  "terms.integrations_strat_1": "Seamless data flow between your workspace, dashboards, and automation tools.",
  "terms.integrations_strat_2": "Robust infrastructure designed for uptime and scalable throughput.",
  "terms.integrations_strat_3": "Transparent information so you can review activity and performance with clarity.",
  "terms.integrations_strat_4": "Advanced analytical capabilities to support informed decision-making within your risk framework.",

  // Privacy Policy (/privacy-policy)
  "privacy.hero_title": "Privacy Policy",
  "privacy.hero_subtitle": "How we collect, use, and protect your personal information",
  "privacy.s1_title": "Storage of your private data",
  "privacy.s1_body":
    "We implement technical and organizational safeguards to help protect your personal information against unauthorized access, disclosure, alteration, or destruction. Data may be stored on secure infrastructure and service providers that support platform operations. While we use commercially reasonable protections, no storage or transmission method can be guaranteed as absolutely secure.",
  "privacy.s2_title": "Information you provide",
  "privacy.s2_body":
    "When you create an account or use Quantro services, you may provide information such as your name, contact details, account profile data, payment and billing details (via payment providers), support requests, and technical information necessary to deliver services.",
  "privacy.s3_title": "Sharing your personal information",
  "privacy.s3_body":
    "We do not sell your personal information. We may share limited data with trusted service providers, integration partners, compliance advisors, or legal authorities when required to operate services, protect users, detect abuse, or comply with law.",
  "privacy.s4_title": "Modifications to this privacy policy",
  "privacy.s4_body":
    "We may revise this Privacy Policy from time to time to reflect product, legal, or operational changes. Updates will be published on this page with an updated effective date where applicable. Continued use of our services after publication indicates acceptance of the updated policy.",
  "privacy.s5_title": "Your rights",
  "privacy.s5_body":
    "Depending on your jurisdiction, you may have rights to access, correct, update, or delete personal data, restrict certain processing, object to processing, or request portability. You may also withdraw consent where processing is consent-based. To submit a privacy request, contact our support team and we will review it in accordance with applicable law.",
  "privacy.s6_title": "Children's privacy",
  "privacy.s6_body":
    "Our services are not directed to children under the age required by applicable law to provide valid consent. We do not knowingly collect personal data from children in violation of applicable law. If you believe a child has provided personal data inappropriately, contact us and we will take reasonable steps to investigate and remove such information where required.",
  "privacy.s7_title": "Social media platforms and websites",
  "privacy.s7_body":
    "Our website or communications may include links to third-party websites, social platforms, and integrations. Those services have independent privacy practices and terms. We are not responsible for third-party content, policies, or security controls. You should review the privacy policies of each external service you use.",
  "privacy.placement_title": "Placement policy",
  "privacy.placement_intro":
    "Platform data and tracking technologies may be used to improve reliability, measure usage, and optimize user experience. Typical examples include:",
  "privacy.place_1": "Session and security cookies to keep your account authenticated.",
  "privacy.place_2": "Performance and analytics signals to improve platform stability.",
  "privacy.place_3": "Essential preferences that remember interface and language choices.",
  "privacy.place_4": "Operational logs used for troubleshooting, abuse prevention, and audit trails.",

  // Language names (dropdown — translated with the rest of the site)
  "lang.en": "English",
  "lang.ur": "Urdu",
  "lang.ar": "Arabic",
  "lang.fr": "French",
  "lang.de": "German",
  "lang.es": "Spanish",
  "lang.it": "Italian",
  "lang.pt": "Portuguese",
  "lang.ru": "Russian",
  "lang.tr": "Turkish",
  "lang.fa": "Persian",
  "lang.hi": "Hindi",
  "lang.bn": "Bengali",
  "lang.zh-CN": "Chinese (Simplified)",
  "lang.zh-TW": "Chinese (Traditional)",
  "lang.ja": "Japanese",
  "lang.ko": "Korean",
  "lang.th": "Thai",
  "lang.vi": "Vietnamese",
  "lang.id": "Indonesian",
  "lang.ms": "Malay",
  "lang.nl": "Dutch",
  "lang.sv": "Swedish",
  "lang.pl": "Polish",
  "lang.uk": "Ukrainian",

  // Dashboard (member area)
  "dash.section_home": "Home",
  "dash.section_personal": "Personal",
  "dash.breadcrumb_dashboard": "Dashboard",
  "dash.nav_portal": "Subscriber Portal",
  "dash.nav_virtual_card": "Virtual Card",
  "dash.nav_wallets": "Crypto Wallets",
  "dash.nav_wallet_connect": "Wallet Connect",
  "dash.nav_convert": "Convert & Spend",
  "dash.nav_fund": "Deposit",
  "dash.nav_membership_plans": "Membership Plans",
  "dash.nav_vault": "EA Vault",
  "dash.nav_withdrawal": "Withdrawal",
  "dash.nav_transactions": "Transactions",
  "dash.nav_live_trades": "EAs Real Time / Live Trades",
  "dash.nav_partnership": "Partnership Program",
  "dash.nav_signals_api": "QN Trading Signals API",
  "dash.nav_profile": "Profile",
  "dash.nav_2fa": "2FA Authentication",
  "dash.nav_kyc": "KYC Verification",
  "dash.nav_reset_password": "Reset Password",
  "dash.exit_website": "← Exit to website",
  "dash.logo_alt": "Quantro Network",
  "dash.search_placeholder": "Search pages...",
  "dash.search_aria": "Search pages",
  "dash.open_menu": "Open menu",
  "dash.close_menu": "Close menu",
  "dash.close_overlay": "Close menu",
  "dash.theme": "Theme",
  "dash.profile": "Profile",
  "dash.notifications": "Notifications",
  "dash.logout": "Log out",
  "dash.chat_support": "Chat support",
  "dash.limited_access_prefix": "Limited Access:",
  "dash.limited_access_rest": "Upgrade to a paid membership for full platform features.",
  "dash.upgrade_now": "Upgrade Now",
  "dash.home_title": "Subscriber Portal",
  "dash.stat_ea_wallet": "EA License Wallet",
  "dash.stat_qn_wallet": "Quantro Network Wallet",
  "dash.stat_subscription_total": "Total Subscription Amount",
  "dash.stat_total_withdrawals": "Total Withdrawals",
  "dash.stat_monthly": "Monthly Earnings",
  "dash.stat_active_eas": "Active EAs",
  "dash.chart_deposits": "Deposits and Withdrawals",
  "dash.chart_monthly": "Monthly Licence Earning",
  "dash.chart_dummy_jul_dec": "Sample data — Oct–Mar",
  "dash.chart_dummy_bars": "Sample data — monthly licence",
  "dash.chart_legend_deposits": "Deposits",
  "dash.chart_legend_withdrawals": "Withdrawals",
  "dash.monthly_current_label": "Current Month",
  "dash.monthly_total_label": "Total Earnings",
  "dash.card_subscription_summary": "Subscription Plan Summary",
  "dash.card_monthly_earnings_trend": "Monthly Earnings Trend",
  "dash.chart_info": "Info",
  "dash.chart_download": "Download",
  "dash.month_jan": "Jan",
  "dash.month_feb": "Feb",
  "dash.month_mar": "Mar",
  "dash.month_jul": "Jul",
  "dash.month_aug": "Aug",
  "dash.month_sep": "Sep",
  "dash.month_oct": "Oct",
  "dash.month_nov": "Nov",
  "dash.month_dec": "Dec",
  "dash.mem.title": "Membership Plans",
  "dash.mem.breadcrumb_dashboard": "Dashboard",
  "dash.mem.wallet_title": "Quantro Network Wallet",
  "dash.mem.wallet_caption": "Available balance for membership purchases",
  "dash.mem.fund_wallet": "Fund Wallet",
  "dash.mem.available_title": "Available Memberships",
  "dash.mem.available_subtitle": "Select a membership plan that suits your needs.",
  "dash.mem.plan_access_title": "ACCESS QUARTERLY",
  "dash.mem.plan_prime_title": "PRIME QUARTERLY",
  "dash.mem.price_access": "$99.00",
  "dash.mem.price_prime": "$199.00",
  "dash.mem.billing_cycle": "3 months",
  "dash.mem.recaptcha": "Complete reCAPTCHA",
  "dash.mem.insufficient": "Insufficient balance",
  "dash.mem.access_f1": "Subscriber portal and EA tools access",
  "dash.mem.access_f2": "Standard support channel",
  "dash.mem.access_f3": "Quarterly license renewal",
  "dash.mem.access_f4": "Community access",
  "dash.mem.access_f5": "Core trading signals",
  "dash.mem.prime_f1": "Everything in Access",
  "dash.mem.prime_f2": "Priority support",
  "dash.mem.prime_f3": "Advanced EA vault",
  "dash.mem.prime_f4": "Higher API limits",
  "dash.mem.prime_f5": "Partner program eligibility",
  "dash.mem.prime_f6": "Premium market insights",
  "dash.fund.page_title": "Deposit",
  "dash.fund.breadcrumb_finance": "Finance",
  "dash.fund.navigate": "Navigate",
  "dash.fund.deposit_title": "Deposit Request",
  "dash.fund.asset_label": "Asset",
  "dash.fund.network_label": "Network",
  "dash.fund.amount_label_crypto": "Amount",
  "dash.fund.amount_placeholder_crypto": "0.00",
  "dash.fund.min_deposit_crypto": "Minimum deposit: 0.0001",
  "dash.fund.submit": "Submit deposit",
  "dash.fund.working": "Submitting...",
  "dash.fund.ok": "Deposit request submitted",
  "dash.fund.err_amount": "Enter a valid amount",
  "dash.fund.err_submit": "Deposit failed",
  "dash.fund.recent_title": "Recent Deposits",
  "dash.fund.col_reference": "Reference",
  "dash.fund.col_amount": "Amount",
  "dash.fund.col_asset": "Asset",
  "dash.fund.col_status": "Status",
  "dash.fund.col_date": "Date",
  "dash.fund.col_action": "Action",
  "dash.fund.empty": "No deposit transactions found",
  "dash.fund.currency_btc": "Bitcoin (BTC)",
  "dash.fund.currency_eth": "Ethereum (ETH)",
  "dash.fund.currency_usdt": "Tether (USDT)",
  "dash.profile.page_title": "My Profile",
  "dash.profile.breadcrumb_dashboard": "Dashboard",
  "dash.profile.edit_photo": "Change profile photo",
  "dash.profile.affiliate_label": "Affiliate Link",
  "dash.profile.copy_link": "Copy affiliate link",
  "dash.profile.copied": "Copied",
  "dash.profile.affiliate_hint": "Share this link to invite new users",
  "dash.profile.details_title": "Personal Details",
  "dash.profile.details_subtitle": "To change your personal details, edit and save",
  "dash.profile.full_name": "Full Name",
  "dash.profile.username": "Username",
  "dash.profile.loading": "Loading…",
  "dash.profile.country": "Country",
  "dash.profile.email": "Email",
  "dash.profile.email_locked": "Email cannot be changed",
  "dash.profile.phone": "Phone",
  "dash.profile.save": "Save Changes",
  "dash.profile.saving": "Saving…",
  "dash.profile.save_ok": "Profile updated",
  "dash.profile.save_fail": "Could not save. Try again.",
  "dash.profile.load_error": "Could not load profile.",
  "dash.profile.password_title": "Change Password",
  "dash.profile.password_subtitle": "Update your password regularly for better security",
  "dash.profile.password_change": "Change",
  "dash.kyc.title": "Submit KYC Documents",
  "dash.kyc.subtitle": "Please upload clear images of your identification documents for verification.",
  "dash.kyc.breadcrumb_dashboard": "Dashboard",
  "dash.kyc.info_size": "Maximum 5MB per image.",
  "dash.kyc.info_formats": "Supported formats: JPG, PNG, GIF.",
  "dash.kyc.info_review": "KYC verification may take 24–48 hours.",
  "dash.kyc.doc_type": "Document Type",
  "dash.kyc.doc_number": "Document Number",
  "dash.kyc.doc_number_placeholder": "Enter document number",
  "dash.kyc.country": "Country of residence",
  "dash.kyc.section_identity": "Identity information",
  "dash.kyc.section_address": "Address and residency",
  "dash.kyc.section_documents": "Document upload",
  "dash.kyc.state": "State",
  "dash.kyc.city": "City",
  "dash.kyc.address_line1": "Street address",
  "dash.kyc.postal_code": "ZIP / Postal code",
  "dash.kyc.dob": "Date of birth",
  "dash.kyc.ssn_last4": "SSN last 4 digits",
  "dash.kyc.us_resident_confirm": "I confirm I am a US resident and data is accurate",
  "dash.kyc.front_label": "Front of Document",
  "dash.kyc.back_label": "Back of Document (if applicable)",
  "dash.kyc.max_size_hint": "Maximum file size: 5MB",
  "dash.kyc.upload_front": "Click to upload front of document",
  "dash.kyc.upload_back": "Click to upload back of document",
  "dash.kyc.drag_hint": "or drag and drop",
  "dash.kyc.submit": "Submit KYC Documents",
  "dash.kyc.submitting": "Submitting...",
  "dash.kyc.submit_ok": "KYC submitted. Review started in mock sandbox.",
  "dash.kyc.submit_error": "Could not submit KYC. Try again.",
  "dash.kyc.status_not_submitted": "KYC not submitted yet.",
  "dash.kyc.status_pending": "KYC is under review.",
  "dash.kyc.status_approved": "KYC approved. You can now apply for virtual card.",
  "dash.kyc.type_national": "National ID Card",
  "dash.kyc.type_passport": "Passport",
  "dash.kyc.type_license": "Driver's License",
  "dash.kyc.error_doc_type": "Please select a document type.",
  "dash.kyc.error_required": "This field is required.",
  "dash.kyc.fix_errors": "Please fix the highlighted errors below.",
  "dash.kyc.error_front": "Please upload the front of your document.",
  "dash.kyc.error_address": "Please provide complete USA address details.",
  "dash.kyc.error_dob": "Please provide date of birth.",
  "dash.kyc.error_ssn_last4": "Please enter valid 4 digit SSN.",
  "dash.kyc.error_us_resident": "US residency confirmation is required.",
  "dash.kyc.error_size": "Each file must be 5MB or smaller.",
  "dash.kyc.error_format": "Use JPG, PNG, or GIF only.",
  "dash.kyc.remove_file": "Remove",
  "dash.tx.title": "Transaction History",
  "dash.tx.breadcrumb_dashboard": "Dashboard",
  "dash.tx.filter_type": "Transaction Type",
  "dash.tx.filter_status": "Status",
  "dash.tx.start_date": "Start Date",
  "dash.tx.end_date": "End Date",
  "dash.tx.all_types": "All Types",
  "dash.tx.all_statuses": "All Statuses",
  "dash.tx.type_deposit": "Deposit",
  "dash.tx.type_withdrawal": "Withdrawal",
  "dash.tx.type_transfer": "Transfer",
  "dash.tx.type_subscription": "Subscription",
  "dash.tx.status_pending": "Pending",
  "dash.tx.status_completed": "Completed",
  "dash.tx.status_failed": "Failed",
  "dash.tx.apply": "Apply Filters",
  "dash.tx.reset": "Reset",
  "dash.tx.col_reference": "Reference",
  "dash.tx.col_type": "Type",
  "dash.tx.col_amount": "Amount",
  "dash.tx.col_status": "Status",
  "dash.tx.col_date": "Date",
  "dash.tx.empty": "No transactions found",
  "dash.vcard.title": "Virtual Debit Card",
  "dash.vcard.subtitle": "Spend online with crypto-backed virtual card (sandbox). US-based users require KYC.",
  "dash.vcard.balance_label": "Available to spend",
  "dash.vcard.balance_fiat": "USD balance",
  "dash.vcard.status_pending_review": "Pending review",
  "dash.vcard.status_active": "Active",
  "dash.vcard.status_frozen": "Frozen",
  "dash.vcard.freeze": "Freeze card",
  "dash.vcard.unfreeze": "Unfreeze card",
  "dash.vcard.pending_action": "Awaiting approval",
  "dash.vcard.pending_hint": "Your card is being issued in sandbox. It will auto-activate shortly.",
  "dash.vcard.apply_title": "Get your virtual card",
  "dash.vcard.apply_body": "Apply once your KYC is approved. Card is issued in test mode for MVP.",
  "dash.vcard.apply_btn": "Apply for virtual card",
  "dash.vcard.kyc_required": "Complete KYC approval to continue with card application.",
  "dash.vcard.goto_kyc": "Go to KYC",
  "dash.vcard.applying": "Creating card...",
  "dash.vcard.masked": "•••• •••• •••• 4242",
  "dash.vcard.expiry": "Expires",
  "dash.vcard.network": "Visa · Virtual",
  "dash.vcard.loading": "Loading your card...",
  "dash.vcard.mock_badge": "Mock Sandbox Mode",
  "dash.vcard.saving": "Updating...",
  "dash.vcard.apply_ok": "Virtual card created in mock sandbox mode.",
  "dash.vcard.freeze_ok": "Card frozen successfully.",
  "dash.vcard.unfreeze_ok": "Card unfrozen successfully.",
  "dash.vcard.err_load": "Could not load card details.",
  "dash.vcard.err_load_tx": "Could not load card activity.",
  "dash.vcard.err_apply": "Could not apply for virtual card.",
  "dash.vcard.err_status": "Could not update card status.",
  "dash.vcard.activity": "Card activity",
  "dash.vcard.empty_activity": "No card transactions yet",
  "dash.vcard.col_merchant": "Merchant",
  "dash.vcard.col_amount": "Amount",
  "dash.vcard.col_status": "Status",
  "dash.vcard.col_date": "Date",
  "dash.vcard.tx_approved": "Approved",
  "dash.vcard.tx_pending": "Pending",
  "dash.vcard.tx_declined": "Declined",
  "dash.wal.title": "Crypto Wallets",
  "dash.wal.subtitle": "USDT & USDC on BNB Chain, and Ethereum — for funding your virtual card and withdrawals.",
  "dash.wal.usdt": "Tether (USDT)",
  "dash.wal.usdt_net": "BNB Smart Chain (BEP-20)",
  "dash.wal.usdc": "USD Coin (USDC)",
  "dash.wal.usdc_net": "BNB Smart Chain (BEP-20)",
  "dash.wal.eth": "Ethereum (ETH)",
  "dash.wal.eth_net": "Ethereum mainnet",
  "dash.wal.balance": "Balance",
  "dash.wal.deposit": "Deposit",
  "dash.wal.withdraw": "Withdraw",
  "dash.wal.history_title": "Wallet activity",
  "dash.wal.col_asset": "Asset",
  "dash.wal.col_type": "Type",
  "dash.wal.col_amount": "Amount",
  "dash.wal.col_status": "Status",
  "dash.wal.col_date": "Date",
  "dash.wal.history_empty": "No wallet activity yet",
  "dash.wal.status_completed": "Completed",
  "dash.wal.status_pending": "Pending",
  "dash.wal.status_failed": "Failed",
  "dash.wal.type_deposit": "Deposit",
  "dash.wal.type_withdraw": "Withdrawal",
  "dash.wal.type_convert": "Convert to card",
  "dash.wal.err_load": "Could not load wallets",
  "dash.wal.err_load_tx": "Could not load wallet activity",
  "dash.wal.err_deposit": "Deposit failed",
  "dash.wal.err_withdraw": "Withdrawal failed",
  "dash.wal.working": "Processing...",
  "dash.wal.deposit_ok": "Mock deposit added successfully",
  "dash.wal.withdraw_ok": "Withdrawal request created",
  "dash.wc.title": "Wallet Connect",
  "dash.wc.subtitle": "Connect your wallet to read on-chain balances for supported tokens on BNB Smart Chain.",
  "dash.wc.connect": "Connect Wallet",
  "dash.wc.disconnect": "Disconnect",
  "dash.wc.connected": "Connected wallet",
  "dash.wc.not_connected": "No wallet connected",
  "dash.wc.network_label": "Network",
  "dash.wc.address_label": "Wallet address",
  "dash.wc.chain_wrong": "Please switch your wallet to BNB Smart Chain (Chain ID 56).",
  "dash.wc.token": "Token",
  "dash.wc.balance": "Balance",
  "dash.wc.status": "Status",
  "dash.wc.status_ready": "Ready",
  "dash.wc.status_loading": "Loading...",
  "dash.wc.status_error": "Could not load balance",
  "dash.wc.status_wrong_network": "Wrong network",
  "dash.wc.empty": "Connect your wallet to view token balances.",
  "dash.wc.project_hint": "Tip: set NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID to enable WalletConnect QR modal.",
  "dash.wc.open_modal": "Open Wallet Connect",
  "dash.wc.modal_title": "Connect your wallet",
  "dash.wc.modal_subtitle": "Connect a wallet provider to continue. We only read your address and token balances.",
  "dash.wc.available_wallets": "Choose a wallet provider below.",
  "dash.wc.connected_with": "Connected with",
  "dash.wc.switch_network": "Switch to BNB Chain",
  "dash.wc.switching": "Switching...",
  "dash.wc.connect_failed": "Wallet connection failed. Please try again.",
  "dash.wc.address_hidden": "Address hidden for privacy",
  "dash.wc.close": "Close",
  "dash.conv.title": "Convert & Spend",
  "dash.conv.subtitle": "Convert crypto to USD for card spending. Rates are indicative in sandbox.",
  "dash.conv.from": "From",
  "dash.conv.to": "To",
  "dash.conv.amount": "Amount",
  "dash.conv.rate": "Indicative rate",
  "dash.conv.receive": "You receive (USD)",
  "dash.conv.cta": "Convert",
  "dash.conv.working": "Converting...",
  "dash.conv.ok": "Converted successfully. Card USD balance updated.",
  "dash.conv.err_amount": "Enter a valid amount",
  "dash.conv.err_convert": "Conversion failed",
  "dash.conv.disclaimer": "Final conversion is processed by the card provider and may differ slightly.",
  "dash.conv.fiat_usd": "USD (card balance)",
  "dash.vault.title": "EA Vault",
  "dash.vault.subtitle": "Manage your expert advisor licenses and downloads.",
  "dash.vault.col_name": "EA Name",
  "dash.vault.col_version": "Version",
  "dash.vault.col_status": "Status",
  "dash.vault.col_expiry": "Expiry",
  "dash.vault.empty": "No EA licenses in your vault",
  "dash.wd.title": "Withdrawal",
  "dash.wd.subtitle": "Withdraw crypto to your external wallet.",
  "dash.wd.asset": "Asset",
  "dash.wd.network": "Network",
  "dash.wd.address": "Destination address",
  "dash.wd.amount": "Amount",
  "dash.wd.submit": "Submit withdrawal",
  "dash.wd.working": "Submitting...",
  "dash.wd.ok": "Withdrawal request submitted",
  "dash.wd.err_amount": "Enter a valid amount",
  "dash.wd.err_address": "Destination address is required",
  "dash.wd.err_submit": "Withdrawal failed",
  "dash.wd.recent": "Recent withdrawals",
  "dash.wd.empty": "No withdrawals yet",
  "dash.live.title": "EAs Real Time / Live Trades",
  "dash.live.subtitle": "Live trade feed from connected strategies (demo).",
  "dash.live.col_pair": "Pair",
  "dash.live.col_side": "Side",
  "dash.live.col_size": "Size",
  "dash.live.col_pnl": "PnL",
  "dash.live.col_time": "Time",
  "dash.live.empty": "No live trades to display",
  "dash.part.title": "Partnership Program",
  "dash.part.subtitle": "Invite users and earn rewards when they subscribe.",
  "dash.part.tier": "Tier",
  "dash.part.commission": "Commission",
  "dash.part.apply": "Apply",
  "dash.part.learn": "Program details will be confirmed with your account manager.",
  "dash.part.t1": "Starter",
  "dash.part.t1c": "5% on referrals",
  "dash.part.t2": "Growth",
  "dash.part.t2c": "10% on referrals",
  "dash.part.t3": "Elite",
  "dash.part.t3c": "15% on referrals",
  "dash.sig.title": "QN Trading Signals API",
  "dash.sig.subtitle": "REST API access for trading signals (sandbox keys).",
  "dash.sig.key_label": "API key",
  "dash.sig.masked": "qn_live_••••••••••••••••",
  "dash.sig.regenerate": "Regenerate key",
  "dash.sig.docs": "Docs",
  "dash.sig.usage": "Usage (30 days)",
  "dash.sig.calls": "API calls",
  "dash.sig.limit": "Rate limit",
  "dash.twofa.title": "Two-Factor Authentication",
  "dash.twofa.subtitle": "Add an extra layer of security to your account.",
  "dash.twofa.enable": "Enable 2FA",
  "dash.twofa.scan": "Scan this QR with Google Authenticator or Authy",
  "dash.twofa.backup": "Backup codes",
  "dash.twofa.verify": "Verify code",
  "dash.twofa.placeholder": "Enter 6-digit code",
  "dash.twofa.save": "Confirm & enable",
  "dash.dpw.title": "Reset Password",
  "dash.dpw.subtitle": "Change your password while logged in.",
  "dash.dpw.current": "Current password",
  "dash.dpw.new": "New password",
  "dash.dpw.confirm": "Confirm new password",
  "dash.dpw.submit": "Update password",
  "dash.dpw.saving": "Updating…",
  "dash.dpw.success": "Password updated successfully.",
  "dash.dpw.error": "Something went wrong. Try again.",
  "dash.placeholder_body":
    "This section is a placeholder. Content will be added when the page is built.",

  // About Us page
  "about.hero.title": "We build wealth creation tools for everyone",
  "about.hero.subtitle":
    "Quantro Network is a premium membership club designed for visionaries who want access to the same automated trading and portfolio tools once reserved for institutions.",
  "about.hero.alt_dashboard": "Trading dashboard on desktop monitor",
  "about.mission.title": "Our mission",
  "about.mission.body":
    "To democratize access to professional-grade trading technology and education—giving every member a clear path from onboarding to execution with tools built for clarity, speed, and long-term performance.",
  "about.vision.title": "Our vision",
  "about.vision.body":
    "A global membership ecosystem where verified data, disciplined automation, and continuous learning work together—so wealth creation is systematic, transparent, and accessible to serious operators worldwide.",
  "about.zenith.section_title": "Unlocking the Future of Algorithmic Trading",
  "about.zenith.name": "Quantro Zenith",
  "about.zenith.body":
    "Zenith is our flagship automation layer—built to coordinate signals, execution logic, and safeguards in one cohesive system so members can deploy strategies with confidence.",
  "about.zenith.b0": "Institutional-style execution workflows",
  "about.zenith.b1": "Risk-aware parameters you control",
  "about.zenith.b2": "Real-time monitoring and analytics",
  "about.zenith.b3": "Designed for consistency across market conditions",
  "about.zenith.alt": "Quantro Zenith product",
  "about.platform.section_title": "Who is the team behind the Platform",
  "about.platform.hours_title": "24/7 Operating Hours",
  "about.platform.hours_body":
    "Markets never sleep—and neither does our infrastructure. Our systems are engineered for continuous operation with monitoring designed to keep your workflows online when it matters most.",
  "about.platform.hours_li1": "Global uptime practices",
  "about.platform.hours_li2": "Operational transparency",
  "about.platform.hours_li3": "Rapid incident response workflows",
  "about.platform.scalable_title": "Scalable and Secure",
  "about.platform.scalable_body":
    "Security and scale go hand in hand: we architect for growth without compromising the fundamentals—permissions, integrity, and member control.",
  "about.platform.scalable_alt": "Platform scalability preview",
  "about.values.section_title": "What we stand for",
  "about.values.transparency.title": "Transparency",
  "about.values.transparency.body":
    "Clear processes, honest communication, and tooling that helps you understand what is happening in your account—without unnecessary noise.",
  "about.values.security.title": "Security",
  "about.values.security.body":
    "Industry-aligned practices for accounts and integrations, with controls designed to help you operate confidently as you scale.",
  "about.values.performance.title": "Performance",
  "about.values.performance.body":
    "Automation and analytics built for disciplined execution—so you can measure outcomes, refine parameters, and stay focused on strategy.",
  "about.mobile.section_title": "Quantro Mobile",
  "about.mobile.subtitle": "Access the markets anywhere, anytime",
  "about.mobile.body":
    "Monitor performance, review activity, and stay connected to your membership tools from your phone—without sacrificing the clarity you expect from the desktop experience.",
  "about.mobile.fast_title": "Always Fast, Always On",
  "about.mobile.fast_body":
    "Lightweight views and responsive layouts keep critical information within reach—whether you are checking in between meetings or on the move.",
  "about.mobile.seamless_title": "Seamless Experience",
  "about.mobile.seamless_body":
    "A consistent design language across web and mobile helps you navigate features quickly—so you spend less time searching and more time executing.",
  "about.mobile.alt": "Quantro mobile application",
  "about.algo.section_title": "Advanced Trading Algorithms",
  "about.algo.body":
    "Our algorithms are engineered for disciplined automation: robust logic, careful validation, and tooling that helps members understand performance—not chase noise.",
  "about.algo.b0": "Multiple strategy profiles for different objectives",
  "about.algo.b1": "Transparent connection to verified market data",
  "about.algo.b2": "Built-in safeguards and configurable parameters",
  "about.algo.b3": "Designed for monitoring and iterative refinement",
  "about.algo.alt": "Advanced algorithms product visual",
  "about.stats.uptime_label": "Uptime",
  "about.stats.support_label": "Support",
  "about.team.title": "The Core Team",
  "about.team.subtitle": "Expertise in Finance",
  "about.team.c1_title": "Financial Modeling",
  "about.team.c1_i0": "Scenario planning",
  "about.team.c1_i1": "Risk-adjusted metrics",
  "about.team.c1_i2": "Portfolio-level views",
  "about.team.c1_i3": "Reporting clarity",
  "about.team.c2_title": "Algorithmic Trading",
  "about.team.c2_i0": "Execution logic",
  "about.team.c2_i1": "Signal validation",
  "about.team.c2_i2": "Live monitoring",
  "about.team.c2_i3": "Iteration workflows",
  "about.team.c3_title": "Data & Infrastructure",
  "about.team.c3_i0": "Connectivity",
  "about.team.c3_i1": "Integrity checks",
  "about.team.c3_i2": "Operational monitoring",
  "about.team.c3_i3": "Scalable architecture",
  "about.team.c4_title": "Member Success",
  "about.team.c4_i0": "Onboarding guidance",
  "about.team.c4_i1": "Education tracks",
  "about.team.c4_i2": "Support workflows",
  "about.team.c4_i3": "Account transparency",
  "about.security.title": "Security First",
  "about.security.body":
    "We treat security as a product requirement—not an afterthought. From account protections to integration hygiene, our goal is to help members operate with confidence while maintaining control over permissions and activity visibility.",
  "about.security.alt": "Quantro Atlas security",
  "about.cta.title": "Ready to get started?",
  "about.cta.subtitle": "Join the membership or sign in to your account.",
  "about.cta.login": "Login",
  "about.cta.signup": "Sign up",

  // Roadmap page
  "roadmap.hero.title": "Quantro Network — Official Product Roadmap (Final Architecture)",
  "roadmap.hero.subtitle":
    "A phased plan from founding and infrastructure through global expansion, enterprise offerings, and community-led governance—built for transparency, security, and long-term member value.",
  "roadmap.vision.title": "Our Vision",
  "roadmap.vision.p1":
    "Quantro Network exists to make institutional-grade automation and verified market connectivity accessible through a membership model that prioritizes education, transparency, and disciplined execution—so members can compound capability over time, not chase noise.",
  "roadmap.vision.p2":
    "This roadmap is our public architecture for delivery: each phase compounds the last, with clear outcomes, measurable milestones, and room to refine as markets and regulation evolve—without losing the trust members place in the platform.",
  "roadmap.timeline_sr": "Product roadmap timeline",
  "roadmap.cta.text": "Ready to get started? Explore our products and services for free today.",
  "roadmap.cta.get_started": "Get Started",
  "roadmap.cta.open_app": "Open App",

  "roadmap.phase1.label": "PHASE 1",
  "roadmap.phase1.title": "Founding, Investing & Initial Infrastructure",
  "roadmap.phase1.desc":
    "Lay the operational and capital foundation for Quantro Network: core team formation, early funding, and baseline infrastructure to support secure member onboarding.",
  "roadmap.phase1.b0": "Incorporate entity structure and governance baseline",
  "roadmap.phase1.b1": "Seed capital allocation and treasury controls",
  "roadmap.phase1.b2": "Core cloud and security posture (accounts, secrets, monitoring)",
  "roadmap.phase1.b3": "Initial member waitlist and compliance documentation",
  "roadmap.phase1.footer": "Outcome: a funded, auditable foundation ready for product build-out.",

  "roadmap.phase2.label": "PHASE 2",
  "roadmap.phase2.title": "Framework Strategy, System Design, and Node Deployment",
  "roadmap.phase2.desc":
    "Translate vision into architecture: trading connectivity, data pipelines, and deployment patterns that scale without sacrificing clarity or control.",
  "roadmap.phase2.b0": "Reference architecture for APIs, EAs, and dashboards",
  "roadmap.phase2.b1": "Staging and production environments with release discipline",
  "roadmap.phase2.b2": "Node topology and redundancy strategy",
  "roadmap.phase2.b3": "Observability: logs, metrics, and alerting playbooks",
  "roadmap.phase2.footer": "Outcome: deployable systems with a documented path to public launch.",

  "roadmap.phase3.label": "PHASE 3",
  "roadmap.phase3.title": "Official Launch, Public Release",
  "roadmap.phase3.desc":
    "Ship the public membership experience: polished onboarding, transparent pricing, and support workflows that match real-world usage at scale.",
  "roadmap.phase3.b0": "Public website, docs, and status communication",
  "roadmap.phase3.b1": "Membership tiers, billing, and account lifecycle",
  "roadmap.phase3.b2": "Support SLAs and escalation paths",
  "roadmap.phase3.b3": "Launch communications and feedback loops",
  "roadmap.phase3.footer": "Outcome: a stable public product with measurable adoption signals.",

  "roadmap.phase4.label": "PHASE 4",
  "roadmap.phase4.title": "Global Growth and System Expansion",
  "roadmap.phase4.desc":
    "Expand reach and capacity: localization, partnerships, and infrastructure growth aligned with member demand and regulatory context.",
  "roadmap.phase4.b0": "Regional onboarding and language coverage",
  "roadmap.phase4.b1": "Partner integrations and co-marketing",
  "roadmap.phase4.b2": "Capacity planning and cost optimization",
  "roadmap.phase4.b3": "Continuous security reviews and pen-test cadence",
  "roadmap.phase4.footer": "Outcome: sustainable global growth without compromising reliability.",

  "roadmap.phase5.label": "PHASE 5",
  "roadmap.phase5.title": "Enterprise & Marketplace Drive",
  "roadmap.phase5.desc":
    "Introduce enterprise-grade offerings and a curated marketplace ecosystem that extends value beyond the core platform.",
  "roadmap.phase5.b0": "Enterprise contracts, SSO, and admin tooling",
  "roadmap.phase5.b1": "Vendor vetting and listing standards",
  "roadmap.phase5.b2": "Revenue share and dispute resolution framework",
  "roadmap.phase5.b3": "Dedicated success and solutions engineering",
  "roadmap.phase5.footer": "Outcome: diversified revenue and a trusted partner ecosystem.",

  "roadmap.phase6.label": "PHASE 6",
  "roadmap.phase6.title": "Community-Led DAO and Continuous State Refinement",
  "roadmap.phase6.desc":
    "Progressively decentralize governance where appropriate while keeping operational excellence: community proposals, treasury transparency, and iterative upgrades.",
  "roadmap.phase6.b0": "Governance forum and proposal lifecycle",
  "roadmap.phase6.b1": "On-chain/off-chain voting and safeguards",
  "roadmap.phase6.b2": "Treasury reporting and audit-friendly disclosures",
  "roadmap.phase6.b3": "Roadmap co-creation with member working groups",
  "roadmap.phase6.footer":
    "Outcome: a resilient network that evolves with its community—safely and predictably.",
};

/** Bump when strings change so cached translations invalidate. */
export const SITE_STRINGS_REVISION = 3;

/** Stable key order for batch translation (must match SITE_STRINGS). */
export const SITE_STRING_KEYS = Object.keys(SITE_STRINGS);

export const NAV_LINKS = [
  { href: "/about-us", labelKey: "nav.about_us" },
  { href: "/roadmap", labelKey: "nav.roadmap" },
  { href: "/membership", labelKey: "nav.membership" },
  { href: "/faqs", labelKey: "nav.faqs" },
];

export const FAQ_ITEM_KEYS = [
  { q: "faq.q0", a: "faq.a0" },
  { q: "faq.q1", a: "faq.a1" },
  { q: "faq.q2", a: "faq.a2" },
  { q: "faq.q3", a: "faq.a3" },
  { q: "faq.q4", a: "faq.a4" },
];

/** Full FAQ page items with category filters: general | billing | technical */
export const FAQ_PAGE_ITEMS = [
  { q: "faq_page.q0", a: "faq_page.a0", category: "general" },
  { q: "faq_page.q1", a: "faq_page.a1", category: "general" },
  { q: "faq_page.q2", a: "faq_page.a2", category: "technical" },
  { q: "faq_page.q3", a: "faq_page.a3", category: "technical" },
  { q: "faq_page.q4", a: "faq_page.a4", category: "general" },
  { q: "faq_page.q5", a: "faq_page.a5", category: "general" },
  { q: "faq_page.q6", a: "faq_page.a6", category: "billing" },
];
